name: push-image
on:
  push:
#    branches:
#      - main
jobs:
  push-node:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/von-image:node-1.12
          context: ./node-1.12
          file: ./node-1.12/Dockerfile.ubuntu
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/von-image:node-1.12
          cache-to: type=inline
          build-args: |
            indy_build_flags=--release
            indy_sdk_url=https://codeload.github.com/hyperledger/indy-sdk/tar.gz/b4b330ef326958d593ab42e25679c2dcd655494c
            indy_sdk_pg_patch_url=https://codeload.github.com/nebucaz/indy-sdk/tar.gz/5e69daabdca5257124a4a28cd68509b9ccd6adb1
            ursa_url=https://codeload.github.com/hyperledger/ursa/tar.gz/394bcdf1413ac41793e96175d46d745ed6ffd970
            rust_version=1.46.0
            rocksdb_lib_ver=5.8.fb
            python_version=3.6.13
            tag_name=ghcr.io/${{ github.repository_owner }}/von-image
            tag_version=node-1.12
